# nginx?? ??? ??? ? ?? ?? ??, swagger api ?? /api/v1 ??? ???? ??
#springdoc:
#  swagger-ui:
#    path: /api/v1/swagger-ui

spring:
  application:
    name: JDQR

  datasource:
    url: jdbc:mysql://13.124.221.144:3306/product?useUnicode=true&characterEncoding=UTF-8
    username: ssafy
    password: zeroticket608
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul


  devtools:
    restart:
      additional-paths: .

  data:
    redis:
      host: redis
      port: 6379


    mongodb:
      uri: mongodb://ssafy:zeroticket608@13.124.221.144:27017/
      database: product

  logging.level:
    org.hibernate.SQL: debug
    org.mongodb.driver: debug

  jwt:
    secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFswvuqoxyve

#  oauth:
#    kakao:
#      client-id: ddd1cb07e0545f2d743ebe394aae68fa
#      redirect_uri : https://j11a607.p.ssafy.io/login/kakao/callback
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
#      client-secret: ZlyVJxR6mF3RnLWh0kEDHazxeuQdiQe3
#      scope: profile_nickname,profile_image, account_email

external:
  token:
    toss: test_sk_Z61JOxRQVEGdzZDnPgkQ8W0X9bAq
  url:
    toss: https://api.tosspayments.com

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION_STATIC}
    stack:
      auto: false